apiVersion: v1
kind: Service
metadata:
  name: service-site-web
  namespace: default
spec:
  selector:
    app: mon-site-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
